/**

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

**/


#pragma once

#include <string>
#include <vector>

class abstract_redis_client {
  public:
    // destructor
    virtual ~abstract_redis_client() {};

    // Basic key-value methods
    virtual void set(std::string key, std::string value) = 0;
    virtual int setnx(std::string key, std::string value) = 0;
    virtual std::string get(std::string key) = 0;
    virtual int del(std::string key) = 0;
    virtual int incr(std::string key) = 0;

    // Expiration methods
    virtual int set_with_expire(std::string key, std::string value, int ttl) = 0;
    virtual int ttl(std::string key) = 0;
    virtual int expire(std::string key, int ttl) = 0;

    // List methods
    virtual int rpush(std::string key, std::vector<std::string> values) = 0;
    virtual int lpush(std::string key, std::vector<std::string> values) = 0;
    virtual std::vector<std::string> lrange(std::string key, int start, int end) = 0;
    virtual int llen(std:: string key) = 0;
    virtual std::string lpop(std::string key) = 0;
    virtual std::string rpop(std::string key) = 0;

    // Set methods
    virtual int sadd(std::string key, std::string value) = 0;
    virtual int srem(std::string key, std::string value) = 0;
    virtual int sismember(std::string key, std::string value) = 0;
    virtual std::vector<std::string> smembers(std::string key) = 0;
    virtual std::vector<std::string> sunion(std::string first_key, std::string second_key) = 0;
};