/**

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

**/


#pragma once
#include "redis_client_abc.h"
#include "resp_abc.h"
#include <string>
#include <memory>
#include <functional>

class redis_client : public abstract_redis_client {
  private:
    std::shared_ptr<abstract_resp> resp_client;
  public:
    redis_client(std::shared_ptr<abstract_resp> client): resp_client(client) {}
    ~redis_client();

    void set(std::string key, std::string value);
    int setnx(std::string key, std::string value);
    std::string get(std::string key);
    int del(std::string key);
    int incr(std::string key);

    // Expiration methods
    int set_with_expire(std::string key, std::string value, int ttl);
    int ttl(std::string key);
    int expire(std::string key, int ttl);

    // List methods
    int rpush(std::string key, std::vector<std::string> values);
    int lpush(std::string key, std::vector<std::string> values);
    std::vector<std::string> lrange(std::string key, int start, int end);
    int llen(std:: string key);
    std::string lpop(std::string key);
    std::string rpop(std::string key);

    // Set methods
    int sadd(std::string key, std::string value);
    int srem(std::string key, std::string value);
    int sismember(std::string key, std::string value);
    std::vector<std::string> smembers(std::string key);
    std::vector<std::string> sunion(std::string first_key, std::string second_key);
    
    // PubSub Methods
    subscriber subscribe(std::string channel, std::function<void (resp_types::subscription_message)> callback);
    subscriber subscribe_sync(std::string channel, std::function<void(resp_types::subscription_message)> callback);
    std::shared_ptr<resp_types::array> transaction(std::vector<resp_types::command> commands);
    std::vector<resp_types::response> send_pipelined(std::vector<resp_types::command> commands);
};