/**

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

**/


#pragma once
#include <string>
#include "resp_abc.h"
#include "resp_types.h"
#include "resp_parser.h"
#include <memory>
#include <iostream>
#include <functional>
#include <map>
#include <thread>
#include "resp_subscriber.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#pragma GCC diagnostic ignored "-Wconversion"
#include "asio.hpp"
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_color_sinks.h"
#pragma GCC diagnostic pop

class resp_client : public abstract_resp {
  private:
    std::shared_ptr<asio::ip::tcp::iostream> redis_stream;
    std::string host;
    int port;
    std::unique_ptr<resp_parser> parser;

  public:
    resp_client(std::string host, int port) {
      this->host = host;
      this->port = port;

      this->redis_stream = std::make_shared<asio::ip::tcp::iostream>(host, std::to_string(port));
      this->parser = std::make_unique<resp_parser>(this->redis_stream);

      spdlog::info("New connection to redis instance '" + this->host + ":" + std::to_string(this->port) + " was created.");
    }

    // Use the in-built "PONG" command
    // to check the connection status
    bool is_connected() {
      try {
        this->send_command(
          resp_types::command({
            "ping"
          })
        );

        return true;
      } catch(std::exception&) {
        return false;
      }
    }

    resp_types::response send_command(resp_types::command command) {
      *this->redis_stream << command.serialize();

      return this->parser->read_resp_message_from_stream();
    }

    void close() {
      this->redis_stream->close();
    }

    std::vector<resp_types::response> send_pipelined(std::vector<resp_types::command> commands) {
      std::string command_concat{};

      for (auto& command : commands) {
        command_concat.append(command.serialize());
      }

      *this->redis_stream << command_concat;

      std::vector<resp_types::response> results{};

      for (int i{0}; i < ((int)commands.size()); i++) {
        results.push_back(this->parser->read_resp_message_from_stream());
      }

      return results;
    }

    subscriber subscribe(std::string channel, std::function<void(resp_types::subscription_message)> callback, bool async) {
      return subscriber{channel, callback, this->host, this->port, async};
    }
    
    ~resp_client() {
      this->redis_stream->close();
    }
};
